#!/bin/bash

# install-docker.sh
# Installs/repairs Docker Engine on WSL distributions (Debian/Ubuntu)
# This script is idempotent - safe to run multiple times
# - Skips installation if Docker is already installed
# - Migrates from old rc.local to binfmt.d configuration
# - Ensures Docker service is running
# Generated by Shortcuts Agent
# Exit Codes:
# 0: Success
# 1: Prereq failure
# 2: Install failure
# 3: Verification failure
# 4: Argument error

USAGE="Usage: $0 --distro-id=<id> --codename=<name> --arch=<arch> --username=<user>"

# 1. Validation
if [ "$EUID" -ne 0 ]; then
  echo "Error: This script must be run as root." >&2
  exit 1
fi

DISTRO_ID=""
CODENAME=""
ARCH=""
TARGET_USER=""

for i in "$@"; do
  case $i in
    --distro-id=*)
      DISTRO_ID="${i#*=}"
      ;;
    --codename=*)
      CODENAME="${i#*=}"
      ;;
    --arch=*)
      ARCH="${i#*=}"
      ;;
    --username=*)
      TARGET_USER="${i#*=}"
      ;;
    *)
      ;;
  esac
done

if [ -z "$DISTRO_ID" ] || [ -z "$CODENAME" ] || [ -z "$ARCH" ] || [ -z "$TARGET_USER" ]; then
    echo "Error: Missing required arguments." >&2
    echo "$USAGE" >&2
    exit 4
fi

log_info() {
    echo -e "\033[0;32m[INFO] $1\033[0m"
}

log_error() {
    echo -e "\033[0;31m[ERROR] $1\033[0m" >&2
}

# 2. Clean State
log_info "Removing conflicting packages..."
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
    apt-get remove -y $pkg 2>/dev/null || true
done

# 3. Prerequisites
log_info "Installing prerequisites..."
install_prereqs() {
    apt-get update -y
    apt-get install -y ca-certificates curl gnupg wget htop
}
install_prereqs || { log_error "Failed to install prerequisites"; exit 2; }

# 4. GPG Key setup
log_info "Setting up Docker GPG key..."
setup_gpg() {
    install -m 0755 -d /etc/apt/keyrings
    rm -f /etc/apt/keyrings/docker.gpg
    curl -fsSL "https://download.docker.com/linux/$DISTRO_ID/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
}
setup_gpg || { log_error "Failed to setup GPG key"; exit 2; }

# 5. Repo Setup
log_info "Setting up Docker repository..."
echo \
  "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$DISTRO_ID \
  $CODENAME stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# 6. Installation (idempotent - checks if already installed)
log_info "Checking Docker installation status..."
if command -v docker >/dev/null 2>&1; then
    DOCKER_VERSION=$(docker --version 2>/dev/null || echo "unknown")
    log_info "Docker is already installed: $DOCKER_VERSION"
    log_info "Skipping installation (script is idempotent)"
else
    log_info "Docker not found, proceeding with installation..."
    install_docker() {
        apt-get update -y
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    }
    install_docker || { log_error "Failed to install Docker packages"; exit 2; }
fi

# 7. User Config (idempotent - checks if already in docker group)
log_info "Configuring user $TARGET_USER..."
configure_user() {
    # Ensure docker group exists
    if ! getent group docker > /dev/null; then
        log_info "Creating docker group..."
        groupadd docker
    fi

    # Check if user is already in docker group
    if id -nG "$TARGET_USER" | grep -qw docker; then
        log_info "User $TARGET_USER is already in docker group"
    else
        log_info "Adding user $TARGET_USER to docker group..."
        usermod -aG docker "$TARGET_USER"
    fi
}
configure_user || { log_error "Failed to configure user"; exit 2; }

# 8. Service (idempotent - checks if already running)
log_info "Ensuring Docker service is running..."
start_service() {
    # Check for systemd
    if pidof systemd > /dev/null; then
        # Enable services if not already enabled
        systemctl enable docker.service 2>/dev/null || true
        systemctl enable containerd.service 2>/dev/null || true

        # Start docker if not already running
        if systemctl is-active --quiet docker; then
            log_info "Docker service is already running"
        else
            log_info "Starting Docker service..."
            systemctl start docker.service
        fi
    else
        # Non-systemd systems
        if service docker status >/dev/null 2>&1; then
            log_info "Docker service is already running"
        else
            log_info "Starting Docker service..."
            service docker start
        fi
    fi
}
start_service || { log_error "Failed to start Docker service"; exit 3; }

# 8.5. Migrate from old rc.local configuration (if present)
log_info "Checking for old rc.local configuration..."
migrate_from_rc_local() {
    local migrated=false

    # Remove /etc/rc.local if it exists
    if [ -f /etc/rc.local ]; then
        log_info "Removing old /etc/rc.local configuration..."
        rm -f /etc/rc.local
        migrated=true
    fi

    # Remove rc-local.service override if it exists
    if [ -f /etc/systemd/system/rc-local.service.d/override.conf ]; then
        log_info "Removing rc-local.service override..."
        rm -f /etc/systemd/system/rc-local.service.d/override.conf
        rmdir --ignore-fail-on-non-empty /etc/systemd/system/rc-local.service.d 2>/dev/null || true
        migrated=true
    fi

    # Disable rc-local service if enabled
    if pidof systemd > /dev/null; then
        if systemctl is-enabled rc-local >/dev/null 2>&1; then
            log_info "Disabling rc-local service..."
            systemctl disable rc-local 2>/dev/null || true
            migrated=true
        fi
    fi

    if [ "$migrated" = true ]; then
        log_info "Migrated from old rc.local configuration to binfmt.d"
    else
        log_info "No old rc.local configuration found (already using binfmt.d or fresh install)"
    fi
}
migrate_from_rc_local || { log_error "Failed to migrate from rc.local"; exit 3; }

# 8.6. Configure WSL interop via binfmt.d (Docker/VS Code compatibility)
log_info "Configuring WSL interop via binfmt.d..."
setup_binfmt_interop() {
    # Create binfmt.d directory if it doesn't exist
    mkdir -p /etc/binfmt.d

    # Check if WSLInterop.conf already exists
    if [ -f /etc/binfmt.d/WSLInterop.conf ]; then
        log_info "WSLInterop.conf already exists, verifying content..."

        # Verify it has the correct content
        if grep -q ":WSLInterop:M::MZ::/init:PF" /etc/binfmt.d/WSLInterop.conf; then
            log_info "WSLInterop.conf is already correctly configured"
        else
            log_info "WSLInterop.conf exists but has different content, updating..."
            echo ":WSLInterop:M::MZ::/init:PF" > /etc/binfmt.d/WSLInterop.conf
        fi
    else
        log_info "Creating WSLInterop.conf..."
        echo ":WSLInterop:M::MZ::/init:PF" > /etc/binfmt.d/WSLInterop.conf
    fi

    # Restart systemd-binfmt to apply changes
    if pidof systemd > /dev/null; then
        systemctl restart systemd-binfmt
    fi
}
setup_binfmt_interop || { log_error "Failed to configure WSL interop via binfmt.d"; exit 3; }

# 9. Verification
log_info "Verifying installation..."
if ! docker --version; then
    log_error "docker command verification failed"
    exit 3
fi

# Try to run hello-world if we are not in a limited test env?
# No, let's just check service status
if pidof systemd > /dev/null; then
    if ! systemctl is-active --quiet docker; then
        log_error "Docker service is not active"
        exit 3
    fi
    # Verify binfmt.d configuration exists
    if [ ! -f /etc/binfmt.d/WSLInterop.conf ]; then
        log_error "WSLInterop.conf not found in /etc/binfmt.d"
        exit 3
    fi

    # Verify WSLInterop is registered in kernel
    if [ ! -e /proc/sys/fs/binfmt_misc/WSLInterop ]; then
        log_error "WSLInterop not registered in binfmt_misc"
        exit 3
    fi

    # Verify systemd-binfmt service is active
    if ! systemctl is-active --quiet systemd-binfmt; then
        log_error "systemd-binfmt service is not active"
        exit 3
    fi
fi

log_info "Docker installation completed successfully!"
exit 0
