#!/bin/bash

# install-docker.sh
# Installs Docker Engine on WSL distributions (Debian/Ubuntu)
# Generated by Shortcuts Agent
# Exit Codes:
# 0: Success
# 1: Prereq failure
# 2: Install failure
# 3: Verification failure
# 4: Argument error

USAGE="Usage: $0 --distro-id=<id> --codename=<name> --arch=<arch> --username=<user>"

# 1. Validation
if [ "$EUID" -ne 0 ]; then
  echo "Error: This script must be run as root." >&2
  exit 1
fi

DISTRO_ID=""
CODENAME=""
ARCH=""
TARGET_USER=""

for i in "$@"; do
  case $i in
    --distro-id=*)
      DISTRO_ID="${i#*=}"
      ;;
    --codename=*)
      CODENAME="${i#*=}"
      ;;
    --arch=*)
      ARCH="${i#*=}"
      ;;
    --username=*)
      TARGET_USER="${i#*=}"
      ;;
    *)
      ;;
  esac
done

if [ -z "$DISTRO_ID" ] || [ -z "$CODENAME" ] || [ -z "$ARCH" ] || [ -z "$TARGET_USER" ]; then
    echo "Error: Missing required arguments." >&2
    echo "$USAGE" >&2
    exit 4
fi

log_info() {
    echo -e "\033[0;32m[INFO] $1\033[0m"
}

log_error() {
    echo -e "\033[0;31m[ERROR] $1\033[0m" >&2
}

# 2. Clean State
log_info "Removing conflicting packages..."
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
    apt-get remove -y $pkg 2>/dev/null || true
done

# 3. Prerequisites
log_info "Installing prerequisites..."
install_prereqs() {
    apt-get update -y
    apt-get install -y ca-certificates curl gnupg
}
install_prereqs || { log_error "Failed to install prerequisites"; exit 2; }

# 4. GPG Key setup
log_info "Setting up Docker GPG key..."
setup_gpg() {
    install -m 0755 -d /etc/apt/keyrings
    rm -f /etc/apt/keyrings/docker.gpg
    curl -fsSL "https://download.docker.com/linux/$DISTRO_ID/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
}
setup_gpg || { log_error "Failed to setup GPG key"; exit 2; }

# 5. Repo Setup
log_info "Setting up Docker repository..."
echo \
  "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$DISTRO_ID \
  $CODENAME stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# 6. Installation
log_info "Installing Docker packages..."
install_docker() {
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}
install_docker || { log_error "Failed to install Docker packages"; exit 2; }

# 7. User Config
log_info "Configuring user $TARGET_USER..."
configure_user() {
    if ! getent group docker > /dev/null; then
        groupadd docker
    fi
    usermod -aG docker "$TARGET_USER"
}
configure_user || { log_error "Failed to configure user"; exit 2; }

# 8. Service
log_info "Starting Docker service..."
start_service() {
    # Check for systemd
    if pidof systemd > /dev/null; then
        systemctl enable docker.service
        systemctl enable containerd.service
        systemctl start docker.service
    else
        service docker start
    fi
}
start_service || { log_error "Failed to start Docker service"; exit 3; }

# 9. Verification
log_info "Verifying installation..."
if ! docker --version; then
    log_error "docker command verification failed"
    exit 3
fi

# Try to run hello-world if we are not in a limited test env? 
# No, let's just check service status
if pidof systemd > /dev/null; then
    if ! systemctl is-active --quiet docker; then
        log_error "Docker service is not active"
        exit 3
    fi
fi

log_info "Docker installation completed successfully!"
exit 0
