#!/bin/bash

# install-podman.sh
# Installs/repairs rootless Podman on WSL distributions (Debian/Ubuntu)
# This script is idempotent - safe to run multiple times
# - Skips installation if Podman is already installed
# - Configures rootless Podman with user socket activation
# - Enables linger for persistent user services
# - Sets environment variables in ~/.bashrc
# Generated by Shortcuts Agent
# Exit Codes:
# 0: Success
# 1: Prereq failure
# 2: Install failure
# 3: Verification failure
# 4: Argument error

USAGE="Usage: $0 --distro-id=<id> --codename=<name> --arch=<arch> --username=<user>"

# 1. Validation
if [ "$EUID" -ne 0 ]; then
  echo "Error: This script must be run as root." >&2
  exit 1
fi

DISTRO_ID=""
CODENAME=""
ARCH=""
TARGET_USER=""

for i in "$@"; do
  case $i in
    --distro-id=*)
      DISTRO_ID="${i#*=}"
      ;;
    --codename=*)
      CODENAME="${i#*=}"
      ;;
    --arch=*)
      ARCH="${i#*=}"
      ;;
    --username=*)
      TARGET_USER="${i#*=}"
      ;;
    *)
      ;;
  esac
done

if [ -z "$DISTRO_ID" ] || [ -z "$CODENAME" ] || [ -z "$ARCH" ] || [ -z "$TARGET_USER" ]; then
    echo "Error: Missing required arguments." >&2
    echo "$USAGE" >&2
    exit 4
fi

log_info() {
    echo -e "\033[0;32m[INFO] $1\033[0m"
}

log_error() {
    echo -e "\033[0;31m[ERROR] $1\033[0m" >&2
}

# 2. Clean conflicting packages (defense-in-depth — PS1 layer already blocks Docker coexistence)
log_info "Removing conflicting packages..."
for pkg in docker.io docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-buildx-plugin; do
    apt-get remove -y $pkg 2>/dev/null || true
done

# 3. Prerequisites
log_info "Installing prerequisites..."
install_prereqs() {
    apt-get update -y
    apt-get install -y ca-certificates curl wget htop
}
install_prereqs || { log_error "Failed to install prerequisites"; exit 2; }

# 4. Podman installation (idempotent - checks if already installed)
log_info "Checking Podman installation status..."
if command -v podman >/dev/null 2>&1; then
    PODMAN_VERSION=$(podman --version 2>/dev/null || echo "unknown")
    log_info "Podman is already installed: $PODMAN_VERSION"
    log_info "Skipping installation (script is idempotent)"
else
    log_info "Podman not found, proceeding with installation..."
    install_podman() {
        apt-get update -y
        apt-get install -y podman slirp4netns uidmap
    }
    install_podman || { log_error "Failed to install Podman packages"; exit 2; }
fi

# 5. User configuration (rootless Podman setup)
log_info "Configuring user $TARGET_USER for rootless Podman..."

# 5a. Enable linger (keeps user systemd services alive after logout)
log_info "Enabling linger for $TARGET_USER..."
enable_linger() {
    loginctl enable-linger "$TARGET_USER"
}
enable_linger || { log_error "Failed to enable linger for $TARGET_USER"; exit 2; }

# 5b. Configure environment variables in ~/.bashrc (idempotent)
log_info "Configuring environment variables in ~/.bashrc..."
TARGET_HOME=$(eval echo "~$TARGET_USER")
BASHRC="$TARGET_HOME/.bashrc"

MARKER_BEGIN="# BEGIN wsl-manager podman"
MARKER_END="# END wsl-manager podman"

configure_bashrc() {
    # Remove existing managed block if present (idempotent overwrite)
    if grep -q "$MARKER_BEGIN" "$BASHRC" 2>/dev/null; then
        sed -i "/$MARKER_BEGIN/,/$MARKER_END/d" "$BASHRC"
        log_info "Removed existing podman block from $BASHRC"
    fi

    # Append managed block
    cat >> "$BASHRC" <<EOF
$MARKER_BEGIN
export XDG_RUNTIME_DIR=/run/user/\$(id -u)
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/\$(id -u)/bus
export DOCKER_HOST=unix:///run/user/\$(id -u)/podman/podman.sock
$MARKER_END
EOF

    chown "$TARGET_USER:$TARGET_USER" "$BASHRC"
    log_info "Podman environment variables configured in $BASHRC"
}
configure_bashrc || { log_error "Failed to configure environment variables"; exit 2; }

# 5c. Enable Podman socket (must run as target user for --user scope)
log_info "Enabling Podman socket for $TARGET_USER..."
enable_socket() {
    su - "$TARGET_USER" -c "systemctl --user enable --now podman.socket"
}
enable_socket || { log_error "Failed to enable Podman socket"; exit 2; }

# 6. cgroups v2 check (warning only — requires Windows-side .wslconfig change)
if [ ! -f /sys/fs/cgroup/cgroup.controllers ]; then
    log_info "WARNING: cgroups v2 is not enabled."
    log_info "For best Podman compatibility, add to Windows .wslconfig:"
    log_info "  [wsl2]"
    log_info "  kernelCommandLine = cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1"
    log_info "Then restart WSL: wsl.exe --shutdown"
fi

# 7. Verification
log_info "Verifying installation..."

# Check podman command works
if ! podman --version; then
    log_error "podman command verification failed"
    exit 3
fi

# Check socket file exists
TARGET_USER_UID=$(id -u "$TARGET_USER")
SOCKET_PATH="/run/user/$TARGET_USER_UID/podman/podman.sock"
if [ ! -S "$SOCKET_PATH" ]; then
    log_error "Podman socket not found at $SOCKET_PATH"
    exit 3
fi

# Check podman info works as target user (validates rootless setup)
if ! su - "$TARGET_USER" -c "podman info" >/dev/null 2>&1; then
    log_error "podman info failed for user $TARGET_USER (rootless setup may be broken)"
    exit 3
fi

log_info "Podman installation completed successfully!"
exit 0
