#!/bin/bash

# install-devpod.sh
# Installs/repairs DevPod CLI on WSL distributions
# This script is idempotent - safe to run multiple times
# - Skips installation if DevPod is already installed
# - Configures the detected container engine as provider
# Generated by Shortcuts Agent
# Exit Codes:
# 0: Success
# 1: Prereq failure
# 2: Install failure
# 3: Verification failure
# 4: Argument error
# 5: No container engine found

USAGE="Usage: $0 --engine=<docker|podman> --username=<user>"

# 1. Validation
if [ "$EUID" -ne 0 ]; then
  echo "Error: This script must be run as root." >&2
  exit 1
fi

ENGINE=""
TARGET_USER=""

for i in "$@"; do
  case $i in
    --engine=*)
      ENGINE="${i#*=}"
      ;;
    --username=*)
      TARGET_USER="${i#*=}"
      ;;
    *)
      ;;
  esac
done

if [ -z "$ENGINE" ] || [ -z "$TARGET_USER" ]; then
    echo "Error: Missing required arguments." >&2
    echo "$USAGE" >&2
    exit 4
fi

log_info() {
    echo -e "\033[0;32m[INFO] $1\033[0m"
}

log_error() {
    echo -e "\033[0;31m[ERROR] $1\033[0m" >&2
}

# 2. Verify container engine is available
log_info "Verifying container engine '$ENGINE' is available..."
if ! command -v "$ENGINE" >/dev/null 2>&1; then
    log_error "Container engine '$ENGINE' not found in PATH"
    exit 5
fi

# 3. DevPod installation (idempotent - checks if already installed)
log_info "Checking DevPod installation status..."
if command -v devpod >/dev/null 2>&1; then
    DEVPOD_VERSION=$(devpod version 2>/dev/null || echo "unknown")
    log_info "DevPod is already installed: $DEVPOD_VERSION"
    log_info "Skipping installation (script is idempotent)"
else
    log_info "DevPod not found, proceeding with installation..."

    # Detect architecture
    MACHINE_ARCH=$(uname -m)
    case "$MACHINE_ARCH" in
        x86_64)
            ARCH="amd64"
            ;;
        aarch64)
            ARCH="arm64"
            ;;
        *)
            log_error "Unsupported architecture: $MACHINE_ARCH"
            exit 1
            ;;
    esac

    log_info "Detected architecture: $ARCH"

    install_devpod() {
        curl -L -o /tmp/devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-$ARCH" && \
        install -c -m 0755 /tmp/devpod /usr/local/bin/devpod && \
        rm -f /tmp/devpod
    }
    install_devpod || { log_error "Failed to download or install DevPod binary"; exit 2; }
fi

# 4. Provider configuration (run as target user - provider config is per-user)
# DevPod always uses the "docker" provider. For Podman, we point the docker
# provider at the podman binary via --option DOCKER_PATH.
log_info "Configuring docker provider for user $TARGET_USER (engine: $ENGINE)..."

configure_provider() {
    if [ "$ENGINE" = "podman" ]; then
        PODMAN_PATH=$(command -v podman)
        su - "$TARGET_USER" -c "devpod provider add docker --option DOCKER_PATH=$PODMAN_PATH 2>/dev/null || true"
    else
        su - "$TARGET_USER" -c "devpod provider add docker 2>/dev/null || true"
    fi
    # Set as active provider
    su - "$TARGET_USER" -c "devpod provider use docker"
}
configure_provider || { log_error "Failed to configure docker provider"; exit 2; }

# 5. Verification
log_info "Verifying installation..."

# Check devpod command works
if ! devpod version >/dev/null 2>&1; then
    log_error "devpod command verification failed"
    exit 3
fi

# Check provider is configured
if ! su - "$TARGET_USER" -c "devpod provider list 2>/dev/null" | grep -q "docker"; then
    log_error "Provider 'docker' not found in devpod provider list"
    exit 3
fi

log_info "DevPod installation completed successfully! (engine: $ENGINE)"
exit 0
