name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:

  test_pwsh:
    name: Unit and Integration Tests (Powershell 7.x)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and run Pester
        run: |
          Write-Output $PSVersionTable
          .\test\bin\init.ps1
          .\test\bin\test-all.ps1 -Coverage
        shell: pwsh

  test_powershell:
    name: Unit and Integration Tests (Powershell 5.x)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install and run Pester
        run: |
          Write-Output $PSVersionTable
          .\test\bin\init.ps1
          .\test\bin\test-all.ps1 -Coverage
        shell: powershell
